steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/alpine-infinity-480716-i4/cloud-run-source-deploy/arela-frontend:latest',
    '--build-arg', 'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${_NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}',
    '.'
  ]
images:
- 'us-central1-docker.pkg.dev/alpine-infinity-480716-i4/cloud-run-source-deploy/arela-frontend:latest'
